### ISSUE TITLE
Allow Book Library filters to appear on mobile

### ISSUE THREAD

**Issue by ashleyfae** [ashleyfae/book-database#233]
WordPress core hides those:

```css
@media screen and (max-width: 782px)
.tablenav .view-switch, .tablenav.top .actions {
    display: none;
}
```

But I'd like them to appear.
